[tool.black]
line-length = 88
target-version = ['py313']

[tool.ruff]
line-length = 79
target-version = "py313"
show-fixes = true

[lint]
preview = true
select = ["E", "F", "I", "C90"]  # Правило I уже включено для сортировки импортов
ignore = [
    "W505",
    "RUF001",
    "RUF002", 
    "PLR1722",
    "T201",
    "S311"
]

[format]
docstring-code-format = true
skip-magic-trailing-comma = false

[lint.pycodestyle]
max-doc-length = 79

[lint.pydocstyle] 
convention = "google"

[lint.isort]
known-first-party = ["my_project"]
lines-after-imports = 2
combine-as-imports = true
split-on-trailing-comma = true
force-wrap-aliases = true
force-single-line = false
# Добавьте эти настройки для лучшей сортировки:
order-by-type = true  # Сортировка по типу импорта (будущее, стандартные, сторонние, локальные)
classes = ["future", "standard-library", "third-party", "first-party", "local-folder"]